branch-defaults:
  main:
    environment: staging-test
    group_suffix: null
global:
  application_name: rails-project
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 3.0 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
